services:
  postgres-test:
    image: postgres:15-alpine
    container_name: lastwar-postgres-test
    environment:
      POSTGRES_DB: lastwar_test
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF8"
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
      - ./lastwar-api/src/test/resources/db/init:/docker-entrypoint-initdb.d
    networks:
      - lastwar-test-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d lastwar_test"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  lastwar-api-test:
    build:
      context: ./lastwar-api
      dockerfile: Dockerfile.test
    container_name: lastwar-api-test
    environment:
      - SPRING_PROFILES_ACTIVE=test
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-test:5432/lastwar_test
      - SPRING_DATASOURCE_USERNAME=test_user
      - SPRING_DATASOURCE_PASSWORD=test_password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
      - SPRING_JPA_SHOW_SQL=true
      - LOGGING_LEVEL_ROOT=INFO
      - LOGGING_LEVEL_MOSCATO_GAME_LASTWAR=DEBUG
    ports:
      - "8081:8080"
    depends_on:
      postgres-test:
        condition: service_healthy
    networks:
      - lastwar-test-network
    volumes:
      - ./lastwar-api/uploads:/app/uploads
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  lastwar-www-test:
    build:
      context: ./lastwar-www
      dockerfile: Dockerfile.test
    container_name: lastwar-www-test
    environment:
      - NODE_ENV=test
      - NEXT_PUBLIC_API_URL=http://lastwar-api-test:8080
      - NEXTAUTH_URL=http://localhost:3001
      - NEXTAUTH_SECRET=test-secret-key-for-testing-only
    ports:
      - "3001:3000"
    depends_on:
      lastwar-api-test:
        condition: service_healthy
    networks:
      - lastwar-test-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  postgres_test_data:
    driver: local

networks:
  lastwar-test-network:
    driver: bridge